### ISSUE TITLE
Use Ownable.sol for selfDestruct() in final project

### ISSUE THREAD

**Issue by tesla809** [simondpalmer/Consensys-Academy-Bootcamp#3]
Can use OpenZeppelin's Ownable.sol to add access rights in self destruct function.

See if you can use it.

**Comment by tesla809** [comment]
Ownable.sol has a function modifier `onlyOwner()`.

If you use this, then you can add to you `design_pattern_decisions.md` the pattern, Restricting Access.

see: 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol

**Comment by simondpalmer** [comment]
Thanks, added now with Restricted Access header
