### ISSUE TITLE
Make sure to never use Mnenomic in this project for any real world assets

### ISSUE THREAD

**Issue by tesla809** [simondpalmer/Consensys-Academy-Bootcamp#6]
It seems that you uploaded your Mnenomic a wallet into your project via uploading .env file. 
WARNING: Do not use this Mnenomic for any real-world assets. 
The same applies to any API keys linked to your accounts.

Usually, .env files are placed into a .gitignore files to avoid sharing sensitive issues.

**Comment by simondpalmer** [comment]
I am aware of this and missed adding it to .gitignore
